# Site settings
title: Hanzi Writer
email: chanindav@gmail.com
description: >
  Hanzi Writer is a free and open-source javascript library
  for Chinese character stroke order animations and practice quizzes
baseurl: "/hanzi-writer" # the subpath of your site, e.g. /blog/
url: "http://chanind.github.io/hanzi-writer" # the base hostname & protocol for your site
github_username:  chanind

# Build settings
markdown: kramdown
exclude:
  - node_modules
  - cdn/*/src
  - cdn/*/demo
  - cdn/*/all.js
  - cdn/*/all.json
  - vendor
  - cdn/*/vendor
  
