# Site settings
title: Hanzi Writer
email: chanindav@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chanind.github.io/hanzi-writer/" # the base hostname & protocol for your site
github_username:  chanind

# Build settings
markdown: kramdown
